services:
  db:
    image: postgres:16
    container_name: ads_db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ads_db}
      POSTGRES_USER: ${POSTGRES_USER:-ads_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ads_password}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ads_web
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    restart: unless-stopped

volumes:
  pgdata:
