# Generated by Django 5.2.5 on 2025-08-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("on_moderation", "На модерации"),
                    ("published", "Опубликовано"),
                    ("archived", "В архиве"),
                ],
                default="on_moderation",
                max_length=20,
            ),
        ),
    ]
